baseUrl = "/"
languageCode = "en-us"
title = "MIT OpenCourseWare"
relativeURLs = false
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/mitodl/ocw-hugo-themes/base-theme"
  [[module.imports]]
    path = "github.com/mitodl/ocw-hugo-themes/www"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"

[caches]
[caches.getjson]
# set getJSON cache age small enough to refresh on every build but large enough to cache usefully within a build
maxAge = "5m"
