baseurl = ""
languageCode = "en-us"
languageLang = "en"
title = "MIT OpenCourseWare"
relativeURLs = false
enableRobotsTXT = true

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[caches]
[caches.getjson]
# set getJSON cache age small enough to refresh on every build but large enough to cache usefully within a build
maxAge = "5m"

[module]
  [[module.imports]]
    path = "github.com/mitodl/ocw-hugo-theme"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"
